export const dataList = [
  {
    id: 1,
    title: "Art",
    bgImage: "/assets/works/Art.webp",
    avatarImage: "/assets/works/artGuy.png",
    image: "/assets/works/art.png",
    projectLink: "/works/art",
    color: "text-[#5b1420]",
    mobileImage: "/assets/works/artMob.png",
  },
  {
    id: 2,
    title: "Education",
    bgImage: "/assets/works/Educational.webp",
    avatarImage: "/assets/works/eduGuy.png",
    image: "/assets/works/edu.png",
    projectLink: "/works/education",
    color: "text-[#734c1d]",
    mobileImage: "/assets/works/eduMob.png",
  },
  {
    id: 3,
    title: "India",
    bgImage: "/assets/works/India.webp",
    avatarImage: "/assets/works/indiaGuy.png",
    image: "/assets/works/india.png",
    projectLink: "/works/india",
    color: "text-[#35ddd6]",
    mobileImage: "/assets/works/indiaMob.png",
  },
  {
    id: 4,
    title: "Uae",
    bgImage: "/assets/works/UAE.webp",
    avatarImage: "/assets/works/uaeGuy.png",
    image: "/assets/works/uae.png",
    projectLink: "/works/uae",
    color: "text-[#5d5c5c]",
    mobileImage: "/assets/works/uaeMob.png",
  },
];
